spring.application.name=killNNwithoutOCR
server.port=8999
# 基础context
server.servlet.context-path=/api/v1

# 上传设置
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 日志
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.aisino=DEBUG
logging.level.com.aisino.openapi.parser.web.interconnected=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/invoice-parser.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
# 发票处理性能配置
invoice.parser.ocr.datapath=d://tmp//tessdata
invoice.parser.ocr.language=chi_sim
invoice.parser.threading.core-pool-size=5
invoice.parser.threading.max-pool-size=10
invoice.parser.threading.queue-capacity=25
invoice.parser.enableOllama=true
invoice.parser.enableSilcom=false
#redis
spring.data.redis.host=10.1.20.101
# Redis服务器地址
# Redis服务器端口
spring.data.redis.port=6379
# Redis数据库索引（默认为0）
spring.data.redis.database=11
# Redis服务器连接密码（默认为空）
spring.data.redis.password=
# 连接池最大连接数（使用负值表示没有限制）
spring.data.redis.lettuce.pool.max-active=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.data.redis.lettuce.pool.max-wait=-1ms
# 连接池中的最大空闲连接
spring.data.redis.lettuce.pool.max-idle=8
# 连接池中的最小空闲连接
spring.data.redis.lettuce.pool.min-idle=0
# 连接超时时间
spring.data.redis.timeout=3000ms


#LLM
deepseek.base-url=https://api.siliconflow.cn/v1/chat/completions
# 秘钥(自己注册硅基的账号，并申请即可)
deepseek.api-key=sk-aaazkvlcdzzqpftlbmlagtgnuhdpmaybkvqxrrsjgdfqlcsg
deepseek.connect-timeout=10

#ollam
spring.ai.ollama.base-url=http://localhost:11434
# 使用已安装的模型名称（如：llama2、mistral等）
spring.ai.ollama.chat.model=glm4:9b


#aop auth
# API 鉴权配置
# 跳过验证的路径列表，用逗号分隔
api.auth.skipAuthPaths=/api/public,/health,/swagger-ui
# 客户端ID和对应的公钥配置
# 格式为: api.auth.clientPublicKeys.{clientId}={publicKey}
api.auth.clientPublicKeys.client1=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
#api.auth.clientPublicKeys.client2=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA

# 请求时间戳有效期（毫秒）
api.auth.timestampValidityMillis=300000
# 签名算法配置
api.auth.signatureAlgorithm=SHA256withRSA
# 日志级别配置
